Feature: Registration on DenimForPiece

Scenario: DenimForPiece Registration scenario

Given User is on home page
When home logo display
Then click on login link
Then click on continue button
Then fill below details on registration page
| Peter | Doran | peter.doran@yopmail.com | 6600 N. Military House | 33496 | Boca Raton | 1111111111 | Tester@123 | Tester@123 |
Then click on continue button and register